# DraftForge Makefile
# Every figure in the writeup must trace to a `make bench` invocation.
# Per parent CLAUDE.md README Standard: "Benchmarks: exact commands to reproduce every number"
#
# Standard targets (CPU-safe unless noted):
#   make setup     — venv + install
#   make lint      — ruff
#   make types     — mypy
#   make test      — pytest
#   make coverage  — pytest + coverage report
#   make audit     — lint + types + test (CI gate, run before every commit)
#   make verify    — bash scripts/verify.sh (walks every CLI)
#   make demo      — local CPU pipeline (scripts/run_demo.py)
#   make figures   — regenerate plots (called by demo)
#   make card      — render HF_CARD.md (release.make_card)
#   make writeup   — validate WRITEUP.md is current (no-op if file present)
#   make all       — setup + audit + demo + card + verify  (no-GPU full artifact set)
#   make onboard   — run scripts/onboard_pod.sh (pod setup)
#   make bench     — full pipeline (scripts/run_full_pipeline.sh) — needs GPU
#   make clean     — remove pyc + caches
#
# Env knobs:
#   PYTHON    python interpreter (default: .venv/bin/python)
#   N_SEEDS   seeds for training (default: 3)
#   SKIP_*    skip pipeline stage (default: 0). See scripts/run_full_pipeline.sh

PYTHON ?= .venv/bin/python
N_SEEDS ?= 3

.PHONY: setup test lint types coverage audit verify demo figures card writeup all onboard bench clean help

help:
	@echo "DraftForge Makefile"
	@echo "  make setup     venv + install"
	@echo "  make test      pytest"
	@echo "  make lint      ruff check"
	@echo "  make types     mypy"
	@echo "  make coverage  pytest + coverage report"
	@echo "  make audit     lint + types + test (CI gate)"
	@echo "  make verify    bash scripts/verify.sh (every CLI binds)"
	@echo "  make demo      local CPU pipeline (scripts/run_demo.py)"
	@echo "  make figures   regenerate plots (eval/plot.py via demo)"
	@echo "  make card      render HF_CARD.md (release.make_card)"
	@echo "  make writeup   validate WRITEUP.md is committed"
	@echo "  make all       setup + audit + demo + card + verify (no-GPU)"
	@echo "  make onboard   pod onboarding (scripts/onboard_pod.sh)"
	@echo "  make bench     full pipeline (scripts/run_full_pipeline.sh) — needs GPU"
	@echo "  make clean     remove caches"

setup:
	python3 -m venv .venv 2>/dev/null || python3.12 -m venv .venv
	.venv/bin/pip install --quiet --upgrade pip
	.venv/bin/pip install --quiet -e ".[train,dev]"

test:
	$(PYTHON) -m pytest -q --no-header

lint:
	ruff check .

types:
	$(PYTHON) -m mypy train ablate serve eval release data

coverage:
	$(PYTHON) -m pytest --cov=train --cov=ablate --cov=serve --cov=eval --cov=release --cov=data --cov-report=term-missing --cov-report=html:htmlcov --cov-report=xml:coverage.xml -q

audit: lint types test
	@echo "audit OK — safe to commit"

verify:
	bash scripts/verify.sh

# demo runs the full local CPU pipeline: data → train-shape → ablate → eval → release.
# It writes synthetic artifacts to results/demo/ (gitignored) so reviewers can
# verify pipeline shape end-to-end without GPU.
demo:
	$(PYTHON) scripts/run_demo.py

# figures is a sub-target of demo; exposed separately so plot regeneration is
# cheap and doesn't re-run the full pipeline.
figures:
	@echo "[figures] regenerated by 'make demo' (no separate script — see scripts/run_demo.py)"
	@test -f results/demo/eval/acceptance_by_batch.png && echo "[figures] OK — see results/demo/eval/" || echo "[figures] NOTE — run 'make demo' first to materialize results/demo/"

# card renders HF_CARD.md at the repo root. Input: release/hf_card.md template
# + results/manifest.json. If manifest.json is missing, falls back to {} (card
# still renders with placeholders substituted).
card:
	@mkdir -p results
	@test -f results/manifest.json || $(PYTHON) -c "import json, pathlib; pathlib.Path('results').mkdir(exist_ok=True); pathlib.Path('results/manifest.json').write_text(json.dumps({'root':'results','note':'placeholder for v1.0 card render'}, indent=2, sort_keys=True))"
	$(PYTHON) -m release.make_card \
		--template release/hf_card.md \
		--results results \
		--head draftforge-eagle3-head \
		--target Qwen/Qwen3-4B \
		--out HF_CARD.md

# writeup just validates that WRITEUP.md is present (it's committed, not generated).
writeup:
	@test -f WRITEUP.md && echo "[writeup] OK — WRITEUP.md is committed" || (echo "[writeup] ERROR — WRITEUP.md missing"; exit 1)

# all = the no-GPU full artifact set. Anyone with a laptop + a venv can run
# `make all` and reproduce every artifact except the trained weights.
all: setup audit demo card writeup verify
	@echo ""
	@echo "[all] complete. Artifacts produced:"
	@echo "  - results/demo/                   CPU pipeline artifacts"
	@echo "  - HF_CARD.md                      rendered HF model card"
	@echo "  - WRITEUP.md                      NeurIPS-style writeup"
	@echo "  - release/head.placeholder.safetensors  (164 bytes; upload_hf.sh refuses)"
	@echo ""
	@echo "[all] GPU-bound (NOT in 'all'): run 'make bench' on a rented H100"
	@echo "      to produce: trained weights, real loss curves, ITL tables, crossover B*."

onboard:
	bash scripts/onboard_pod.sh

bench:
	N_SEEDS=$(N_SEEDS) bash scripts/run_full_pipeline.sh

clean:
	rm -rf .pytest_cache .ruff_cache .mypy_cache htmlcov coverage.xml .coverage
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	rm -rf examples/_out
